/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package MainPackage;


import java.awt.*;
import javax.swing.*;
import java.awt.Color;
import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;

/**
 *
 * @author theola1
 */
public class PanelRaknare extends javax.swing.JPanel {

   public static double XMax=5; //XMax är det valda största x-värdet som ritaren ska rita mellan
   public static double XMin=-XMax; //default är att rita med negativa x och y
   double XNu=0; //XNu är det nuvarande xVärdet
   double XIncrease=0; //Anger hur mycket X ska öka per pixel åt höger
   String tillfälligkör="";
   String ul="";
   double[] ytalfält = new double[640];
   String yHalvorPlus="";
   String yHalvorMinus="";
   String yHelaPlus="";
   String yHelaMinus="";
   String yTreFyraPlus="";
   String yFyraPlus="";
   
   String xHalvorPlus="";
   String xHalvorMinus="";
   String xHelaPlus="";
   String xHelaMinus="";
   String xTreFyraPlus="";
   String xFyraPlus="";
   
   boolean RitaYNegativa=true;
   boolean RitaXNegativa=true;
    
   public static double YMax=10;
   public static double YMin=-YMax; //default är att rita med negativa x och y
    
   static final ScriptEngineManager manager = new ScriptEngineManager();
   static final ScriptEngine motor = manager.getEngineByName("JavaScript");
   String Kör = "";
    
    /**
    public static String Kör = "";
    /**
     * Creates new form PanelRaknare
     */
    public PanelRaknare() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FieldFunctions = new javax.swing.JTextField();
        Bttn1 = new javax.swing.JButton();
        Bttn2 = new javax.swing.JButton();
        Bttn3 = new javax.swing.JButton();
        Bttn4 = new javax.swing.JButton();
        Bttn5 = new javax.swing.JButton();
        Bttn6 = new javax.swing.JButton();
        Bttn7 = new javax.swing.JButton();
        Bttn8 = new javax.swing.JButton();
        Bttn9 = new javax.swing.JButton();
        Bttn0 = new javax.swing.JButton();
        BttnPunkt = new javax.swing.JButton();
        BttnClear = new javax.swing.JButton();
        BttnRun = new javax.swing.JButton();
        BttnBack = new javax.swing.JButton();
        BttnPlus = new javax.swing.JButton();
        BttnMinus = new javax.swing.JButton();
        BttnMulti = new javax.swing.JButton();
        BttnDivi = new javax.swing.JButton();
        BttnPower = new javax.swing.JButton();
        BttnParantes1 = new javax.swing.JButton();
        BttnParantes2 = new javax.swing.JButton();
        BttnX = new javax.swing.JButton();
        LabelSyntax = new javax.swing.JLabel();
        BttnKomma = new javax.swing.JButton();
        BttnCos = new javax.swing.JButton();
        BttnSin = new javax.swing.JButton();
        LabelSpeglaY = new javax.swing.JLabel();
        bttnYJa = new javax.swing.JButton();
        BttnYNej = new javax.swing.JButton();
        LabelSpeglaX = new javax.swing.JLabel();
        BttnXJa = new javax.swing.JButton();
        BttnXNej = new javax.swing.JButton();
        BttnTan = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(640, 660));
        setMinimumSize(new java.awt.Dimension(640, 660));
        setPreferredSize(new java.awt.Dimension(640, 180));

        FieldFunctions.setEditable(false);

        Bttn1.setText("1");
        Bttn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn1ActionPerformed(evt);
            }
        });

        Bttn2.setText("2");
        Bttn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn2ActionPerformed(evt);
            }
        });

        Bttn3.setText("3");
        Bttn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn3ActionPerformed(evt);
            }
        });

        Bttn4.setText("4");
        Bttn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn4ActionPerformed(evt);
            }
        });

        Bttn5.setText("5");
        Bttn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn5ActionPerformed(evt);
            }
        });

        Bttn6.setText("6");
        Bttn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn6ActionPerformed(evt);
            }
        });

        Bttn7.setText("7");
        Bttn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn7ActionPerformed(evt);
            }
        });

        Bttn8.setText("8");
        Bttn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn8ActionPerformed(evt);
            }
        });

        Bttn9.setText("9");
        Bttn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn9ActionPerformed(evt);
            }
        });

        Bttn0.setText("0");
        Bttn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn0ActionPerformed(evt);
            }
        });

        BttnPunkt.setText(".");
        BttnPunkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnPunktActionPerformed(evt);
            }
        });

        BttnClear.setText("C");
        BttnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnClearActionPerformed(evt);
            }
        });

        BttnRun.setText("Kör");
        BttnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnRunActionPerformed(evt);
            }
        });

        BttnBack.setText("←");
        BttnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnBackActionPerformed(evt);
            }
        });

        BttnPlus.setText("+");
        BttnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnPlusActionPerformed(evt);
            }
        });

        BttnMinus.setText("-");
        BttnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnMinusActionPerformed(evt);
            }
        });

        BttnMulti.setText("*");
        BttnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnMultiActionPerformed(evt);
            }
        });

        BttnDivi.setText("/");
        BttnDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnDiviActionPerformed(evt);
            }
        });

        BttnPower.setText("^");
        BttnPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnPowerActionPerformed(evt);
            }
        });

        BttnParantes1.setText("(");
        BttnParantes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnParantes1ActionPerformed(evt);
            }
        });

        BttnParantes2.setText(")");
        BttnParantes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnParantes2ActionPerformed(evt);
            }
        });

        BttnX.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        BttnX.setText("X");
        BttnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnXActionPerformed(evt);
            }
        });

        LabelSyntax.setText("Syntax: Math.pow(X, Y) = X^Y; ange vinklar i radianer.");

        BttnKomma.setText(",");
        BttnKomma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnKommaActionPerformed(evt);
            }
        });

        BttnCos.setText("Cos");
        BttnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnCosActionPerformed(evt);
            }
        });

        BttnSin.setText("Sin");
        BttnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnSinActionPerformed(evt);
            }
        });

        LabelSpeglaY.setText("Visa negativa Y-värden?");

        bttnYJa.setText("Ja");
        bttnYJa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnYJaActionPerformed(evt);
            }
        });

        BttnYNej.setText("Nej");
        BttnYNej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnYNejActionPerformed(evt);
            }
        });

        LabelSpeglaX.setText("Visa negativa X-värden?");

        BttnXJa.setText("Ja");
        BttnXJa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnXJaActionPerformed(evt);
            }
        });

        BttnXNej.setText("Nej");
        BttnXNej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnXNejActionPerformed(evt);
            }
        });

        BttnTan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BttnTan.setText("Tan");
        BttnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnTanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelSpeglaY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttnYJa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BttnYNej))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(0, 38, Short.MAX_VALUE)
                                    .addComponent(BttnRun)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(FieldFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LabelSpeglaX)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BttnXJa)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BttnXNej)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BttnParantes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BttnX, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelSyntax)
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BttnCos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BttnSin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BttnTan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BttnParantes2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(BttnKomma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BttnDivi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(BttnMulti))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Bttn4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bttn5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bttn6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Bttn0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(Bttn1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Bttn2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Bttn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BttnPunkt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Bttn7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bttn8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bttn9)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BttnClear)
                    .addComponent(BttnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BttnPlus)
                    .addComponent(BttnPower))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FieldFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BttnRun))
                        .addGap(18, 18, 18)
                        .addComponent(LabelSyntax)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelSpeglaY)
                            .addComponent(bttnYJa)
                            .addComponent(BttnYNej))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelSpeglaX)
                            .addComponent(BttnXJa)
                            .addComponent(BttnXNej)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BttnMinus)
                            .addComponent(BttnMulti)
                            .addComponent(BttnKomma)
                            .addComponent(BttnDivi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bttn7)
                            .addComponent(Bttn8)
                            .addComponent(Bttn9)
                            .addComponent(BttnParantes2)
                            .addComponent(BttnParantes1)
                            .addComponent(BttnPower))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bttn4)
                            .addComponent(Bttn5)
                            .addComponent(Bttn6)
                            .addComponent(BttnPlus)
                            .addComponent(BttnCos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Bttn1)
                                    .addComponent(Bttn2)
                                    .addComponent(Bttn3)
                                    .addComponent(BttnSin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Bttn0)
                                    .addComponent(BttnPunkt)
                                    .addComponent(BttnTan)))
                            .addComponent(BttnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BttnBack)
                        .addComponent(BttnX, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 546, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
      
    public void funktionKor()
    {
        if (RitaYNegativa==true)
        {
            YMin=-YMax;
        }
        
        else if (RitaYNegativa==false)
        {
            YMin=0;
        }
        
        if (RitaXNegativa==true)
        {
            XMin=-XMax;
        }
        
        else if (RitaXNegativa==false)
        {
            XMin=0;
        }
         
        XNu = XMin; //börjar med att sätta värdet i XNu till det minsta Xvärde som ska användas
        XIncrease= (XMax-XMin)/640;         
       
        for (int i=0; i<640; i++)
        {
            ul=String.valueOf(XNu);
           tillfälligkör=Kör;
           tillfälligkör=tillfälligkör.replace("X", ul); //} catch (NullPointerException e){}
          
           for (int a=0; a<tillfälligkör.length(); a++) //Ser till att t.ex. 5--5=10 funkar
           {
                if (tillfälligkör.charAt(a)=='-' && tillfälligkör.charAt(a+1)=='-')
                {
                String sträng11 = tillfälligkör.substring(0, a);
		String sträng12 = tillfälligkör.substring(a+2, tillfälligkör.length());
		tillfälligkör = sträng11+"+"+sträng12;
                }
                
                else if (tillfälligkör.charAt(a)=='-' && tillfälligkör.charAt(a+1)=='(' && tillfälligkör.charAt(a+2)=='-')
                {
                String sträng11 = tillfälligkör.substring(0, a);
		String sträng12 = tillfälligkör.substring(a+3, tillfälligkör.length());
		tillfälligkör = sträng11+"+("+sträng12;
                }
            }
            try {
                ytalfält[i] = (double)motor.eval(tillfälligkör);
            } catch (ScriptException ex) {
                Logger.getLogger(PanelRaknare.class.getName()).log(Level.SEVERE, null, ex);
            }
                
            XNu+=XIncrease;
        }        
        
        yHalvorPlus=String.valueOf(YMax/2);
        yHalvorMinus="-"+yHalvorPlus;
        yHelaPlus=String.valueOf(YMax);
        yHelaMinus="-"+yHelaPlus;
        yTreFyraPlus=String.valueOf(3*YMax/4);
        yFyraPlus=String.valueOf(YMax/4);
        
        xHalvorPlus=String.valueOf(XMax/2);
        xHalvorMinus="-"+xHalvorPlus;
        xHelaPlus=String.valueOf(XMax);
        xHelaMinus="-"+xHelaPlus;
        xTreFyraPlus=String.valueOf(3*XMax/4);
        xFyraPlus=String.valueOf(XMax/4);
       
    } 
    private void Bttn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn9ActionPerformed
         FieldFunctions.setText(FieldFunctions.getText()+"9"); //Adds the number "9" to the textfield
    }//GEN-LAST:event_Bttn9ActionPerformed

    private void BttnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnClearActionPerformed
        FieldFunctions.setText("");
    }//GEN-LAST:event_BttnClearActionPerformed

    private void Bttn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn0ActionPerformed
      
        FieldFunctions.setText(FieldFunctions.getText()+"0"); //Adds the number "0" to the textfield
    }//GEN-LAST:event_Bttn0ActionPerformed

    private void BttnPunktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnPunktActionPerformed
         FieldFunctions.setText(FieldFunctions.getText()+"."); //Adds a "." to the textfield
    }//GEN-LAST:event_BttnPunktActionPerformed

    private void BttnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnPlusActionPerformed
      FieldFunctions.setText(FieldFunctions.getText()+"+"); //Adds a "+" to the textfield
    }//GEN-LAST:event_BttnPlusActionPerformed

    private void Bttn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn1ActionPerformed
      FieldFunctions.setText(FieldFunctions.getText()+"1"); //Adds the number "1" to the textfield
    }//GEN-LAST:event_Bttn1ActionPerformed

    private void Bttn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn2ActionPerformed
      FieldFunctions.setText(FieldFunctions.getText()+"2"); //Adds the number "2" to the textfield
    }//GEN-LAST:event_Bttn2ActionPerformed

    private void Bttn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn3ActionPerformed
      FieldFunctions.setText(FieldFunctions.getText()+"3"); //Adds the number "3" to the textfield
    }//GEN-LAST:event_Bttn3ActionPerformed

    private void BttnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnMinusActionPerformed
      FieldFunctions.setText(FieldFunctions.getText()+"-"); //Adds a "-" to the textfield
    }//GEN-LAST:event_BttnMinusActionPerformed

    private void Bttn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn4ActionPerformed
      FieldFunctions.setText(FieldFunctions.getText()+"4"); //Adds the number "4" to the textfield
    }//GEN-LAST:event_Bttn4ActionPerformed

    private void Bttn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn5ActionPerformed
     FieldFunctions.setText(FieldFunctions.getText()+"5"); //Adds the number "5" to the textfield
    }//GEN-LAST:event_Bttn5ActionPerformed

    private void Bttn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn6ActionPerformed
      FieldFunctions.setText(FieldFunctions.getText()+"6"); //Adds the number "6" to the textfield
    }//GEN-LAST:event_Bttn6ActionPerformed

    private void BttnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnMultiActionPerformed
      FieldFunctions.setText(FieldFunctions.getText()+"*"); //Adds a "*" to the textfield
    }//GEN-LAST:event_BttnMultiActionPerformed

    private void Bttn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn7ActionPerformed
     FieldFunctions.setText(FieldFunctions.getText()+"7"); //Adds the number "7" to the textfield
    }//GEN-LAST:event_Bttn7ActionPerformed

    private void Bttn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn8ActionPerformed
     FieldFunctions.setText(FieldFunctions.getText()+"8"); //Adds the number "8" to the textfield
    }//GEN-LAST:event_Bttn8ActionPerformed

    private void BttnDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnDiviActionPerformed
      FieldFunctions.setText(FieldFunctions.getText()+"/"); //Adds a "/" to the textfield
    }//GEN-LAST:event_BttnDiviActionPerformed

    private void BttnPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnPowerActionPerformed
  //  FieldFunctions.setText(FieldFunctions.getText()+"^"); //Adds a "^" to the textfield - äldre version där inmatningssekvensen var x^,y.
   /* String langdstring = FieldFunctions.getText();
    int langd = langdstring.length();
    String tillfällig1 = langdstring.substring(langd-1);
    String tillfällig3 = langdstring.substring(0, langd-1); 
    String tillfällig2 = "Math.pow("+tillfällig1;
    FieldFunctions.setText(tillfällig3+tillfällig2);*/
     FieldFunctions.setText(FieldFunctions.getText()+"Math.pow("); //Adds a "Math.pow(" to the textfield - nyare, enklare version
    }//GEN-LAST:event_BttnPowerActionPerformed

    private void BttnParantes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnParantes2ActionPerformed
       FieldFunctions.setText(FieldFunctions.getText()+")"); //Adds a ")" to the textfield
    }//GEN-LAST:event_BttnParantes2ActionPerformed

    private void BttnParantes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnParantes1ActionPerformed
      FieldFunctions.setText(FieldFunctions.getText()+"("); //Adds a "(" to the textfield
    }//GEN-LAST:event_BttnParantes1ActionPerformed

    private void BttnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnXActionPerformed
      FieldFunctions.setText(FieldFunctions.getText()+"X"); //Adds an "X" to the textfield
    }//GEN-LAST:event_BttnXActionPerformed

    private void BttnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnRunActionPerformed
    Kör=FieldFunctions.getText();
    funktionKor();
    repaint();
    
    
    }//GEN-LAST:event_BttnRunActionPerformed

    private void BttnKommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnKommaActionPerformed
      FieldFunctions.setText(FieldFunctions.getText()+","); //Adds an "," to the textfield
    }//GEN-LAST:event_BttnKommaActionPerformed

    private void BttnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnBackActionPerformed
     String Bort = FieldFunctions.getText();
     int langdBort = Bort.length();
     Bort = Bort.substring(0, langdBort-1);
     FieldFunctions.setText(Bort);
    }//GEN-LAST:event_BttnBackActionPerformed

    private void BttnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnCosActionPerformed
    FieldFunctions.setText(FieldFunctions.getText()+"Math.cos("); //Adds a Math.cos( to the function
    }//GEN-LAST:event_BttnCosActionPerformed

    private void BttnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnSinActionPerformed
     FieldFunctions.setText(FieldFunctions.getText()+"Math.sin("); //Adds a Math.sin( to the function
    }//GEN-LAST:event_BttnSinActionPerformed

    private void bttnYJaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnYJaActionPerformed
    RitaYNegativa=true;
    }//GEN-LAST:event_bttnYJaActionPerformed

    private void BttnYNejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnYNejActionPerformed
    RitaYNegativa=false;
    }//GEN-LAST:event_BttnYNejActionPerformed

    private void BttnXJaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnXJaActionPerformed
    RitaXNegativa=true;
    }//GEN-LAST:event_BttnXJaActionPerformed

    private void BttnXNejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnXNejActionPerformed
    RitaXNegativa=false;
    }//GEN-LAST:event_BttnXNejActionPerformed

    private void BttnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnTanActionPerformed
    FieldFunctions.setText(FieldFunctions.getText()+"Math.tan("); //Adds a Math.tan( to the function
    }//GEN-LAST:event_BttnTanActionPerformed

   protected void paintComponent(Graphics g){
        super.paintComponent(g);
        g.setColor(Color.BLACK);
        double var=480/(YMax-YMin);
        
        if (XMin==-XMax)
        {g.fillRect(320, 180, 5, 485);}
        else {g.fillRect(1, 180, 5, 485);}
       
        if(YMin==-YMax)
        { g.fillRect(1, 420, 640, 5); 
            for (int k=0; k<640; k++)
             {
                 if((int)(420-(var*ytalfält[k])+0.5)>179 && (int)(420-(var*ytalfält[k])+0.5)<661)
                 {g.setColor(Color.CYAN); g.fillRect(k+1, (int)(420-(var*ytalfält[k])+0.5), 5, 5);}
             }
        }
        else 
        { g.fillRect(1, 660, 640, 5);
            for (int k=0; k<640; k++)
             {
                if((int)(660-(var*ytalfält[k])+0.5)>179 && (int)(660-(var*ytalfält[k])+0.5)<661)
                {g.setColor(Color.CYAN); g.fillRect(k+1, (int)(660-(var*ytalfält[k])+0.5), 5, 5);}
             } 
        }
       // FÖLJANDE KOD FIXAR GRADERINGAR OCH AXLAR 
      if (YMin==-YMax && XMin==-XMax)
      {    
          g.setColor(Color.BLACK);
          g.fillRect(310, 300, 25, 3);   g.drawString(yHalvorPlus, 340, 303); 
          g.fillRect(310, 540, 25, 3);   g.drawString(yHalvorMinus, 340, 543); 
          g.fillRect(310, 180, 25, 3);   g.drawString(yHelaPlus, 340, 183);
          g.fillRect(310, 662, 25, 3);   g.drawString(yHelaMinus, 340, 663); 
         
          g.fillRect(0, 410, 3, 25);     g.drawString(xHelaMinus, 0, 405); 
          g.fillRect(160, 410, 3, 25);   g.drawString(xHalvorMinus, 150, 405); 
          g.fillRect(480, 410, 3, 25);   g.drawString(xHalvorPlus, 470, 405);
          g.fillRect(642, 410, 3, 25);   g.drawString(xHelaPlus, 630, 405);
          
      }
      else if (YMin==0 && XMin==-XMax)
      {    
          g.setColor(Color.BLACK);
          g.fillRect(310, 300, 25, 3);   g.drawString(yTreFyraPlus, 340, 303); 
          g.fillRect(310, 540, 25, 3);   g.drawString(yFyraPlus, 340, 543); 
          g.fillRect(310, 180, 25, 3);   g.drawString(yHelaPlus, 340, 183);
          g.fillRect(310, 420, 25, 3);   g.drawString(yHalvorPlus, 340, 423);
          
          g.fillRect(0, 650, 3, 25);     g.drawString(xHelaMinus, 0, 645); 
          g.fillRect(160, 650, 3, 25);   g.drawString(xHalvorMinus, 150, 645); 
          g.fillRect(480, 650, 3, 25);   g.drawString(xHalvorPlus, 470, 645);
          g.fillRect(640, 650, 3, 25);   g.drawString(xHelaPlus, 630, 645);
          
      }
      
      else if (YMin==0 && XMin==0)
      {
          g.setColor(Color.BLACK);
          g.fillRect(0, 300, 10, 3);   g.drawString(yTreFyraPlus, 20, 303); 
          g.fillRect(0, 540, 10, 3);   g.drawString(yFyraPlus, 20, 543); 
          g.fillRect(0, 180, 10, 3);   g.drawString(yHelaPlus, 20, 183);
          g.fillRect(0, 420, 10, 3);   g.drawString(yHalvorPlus, 20, 423);
          
          g.fillRect(320, 650, 3, 25);   g.drawString(xHalvorPlus, 310, 645); 
          g.fillRect(160, 650, 3, 25);   g.drawString(xFyraPlus, 150, 645); 
          g.fillRect(480, 650, 3, 25);   g.drawString(xTreFyraPlus, 470, 645);
          g.fillRect(640, 650, 3, 25);   g.drawString(xHelaPlus, 630, 645);
      }
       
      else if (YMin==-YMax && XMin==0)
      {
          g.setColor(Color.BLACK);
          g.fillRect(0, 300, 10, 3);   g.drawString(yHalvorPlus, 20, 303); 
          g.fillRect(0, 540, 10, 3);   g.drawString(yHalvorMinus, 20, 543); 
          g.fillRect(0, 180, 10, 3);   g.drawString(yHelaPlus, 20, 183);
          g.fillRect(0, 660, 10, 3);   g.drawString(yHelaMinus, 20, 663); 
          
          g.fillRect(320, 410, 3, 25);   g.drawString(xHalvorPlus, 310, 405); 
          g.fillRect(160, 410, 3, 25);   g.drawString(xFyraPlus, 150, 405); 
          g.fillRect(480, 410, 3, 25);   g.drawString(xTreFyraPlus, 470, 405);
          g.fillRect(640, 410, 3, 25);   g.drawString(xHelaPlus, 630, 405);
      }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bttn0;
    private javax.swing.JButton Bttn1;
    private javax.swing.JButton Bttn2;
    private javax.swing.JButton Bttn3;
    private javax.swing.JButton Bttn4;
    private javax.swing.JButton Bttn5;
    private javax.swing.JButton Bttn6;
    private javax.swing.JButton Bttn7;
    private javax.swing.JButton Bttn8;
    private javax.swing.JButton Bttn9;
    private javax.swing.JButton BttnBack;
    private javax.swing.JButton BttnClear;
    private javax.swing.JButton BttnCos;
    private javax.swing.JButton BttnDivi;
    private javax.swing.JButton BttnKomma;
    private javax.swing.JButton BttnMinus;
    private javax.swing.JButton BttnMulti;
    private javax.swing.JButton BttnParantes1;
    private javax.swing.JButton BttnParantes2;
    private javax.swing.JButton BttnPlus;
    private javax.swing.JButton BttnPower;
    private javax.swing.JButton BttnPunkt;
    private javax.swing.JButton BttnRun;
    private javax.swing.JButton BttnSin;
    private javax.swing.JButton BttnTan;
    private javax.swing.JButton BttnX;
    private javax.swing.JButton BttnXJa;
    private javax.swing.JButton BttnXNej;
    private javax.swing.JButton BttnYNej;
    private javax.swing.JTextField FieldFunctions;
    private javax.swing.JLabel LabelSpeglaX;
    private javax.swing.JLabel LabelSpeglaY;
    private javax.swing.JLabel LabelSyntax;
    private javax.swing.JButton bttnYJa;
    // End of variables declaration//GEN-END:variables
}
