/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package MainPackage;

/**
 *
 * @author theola1
 */
public class PanelXMax extends javax.swing.JPanel {

    /**
     * Creates new form PanelYMax
     */
    public PanelXMax() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bttn7 = new javax.swing.JButton();
        BttnPunkt = new javax.swing.JButton();
        Bttn8 = new javax.swing.JButton();
        Bttn9 = new javax.swing.JButton();
        Bttn6 = new javax.swing.JButton();
        Bttn5 = new javax.swing.JButton();
        Bttn4 = new javax.swing.JButton();
        Bttn1 = new javax.swing.JButton();
        Bttn2 = new javax.swing.JButton();
        Bttn3 = new javax.swing.JButton();
        Bttn0 = new javax.swing.JButton();
        FieldXMax = new javax.swing.JTextField();
        LabelXMax = new javax.swing.JLabel();
        BttnKlar = new javax.swing.JButton();
        BttnClear = new javax.swing.JButton();
        BttnBack = new javax.swing.JButton();

        Bttn7.setText("7");
        Bttn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn7ActionPerformed(evt);
            }
        });

        BttnPunkt.setText(".");
        BttnPunkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnPunktActionPerformed(evt);
            }
        });

        Bttn8.setText("8");
        Bttn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn8ActionPerformed(evt);
            }
        });

        Bttn9.setText("9");
        Bttn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn9ActionPerformed(evt);
            }
        });

        Bttn6.setText("6");
        Bttn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn6ActionPerformed(evt);
            }
        });

        Bttn5.setText("5");
        Bttn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn5ActionPerformed(evt);
            }
        });

        Bttn4.setText("4");
        Bttn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn4ActionPerformed(evt);
            }
        });

        Bttn1.setText("1");
        Bttn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn1ActionPerformed(evt);
            }
        });

        Bttn2.setText("2");
        Bttn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn2ActionPerformed(evt);
            }
        });

        Bttn3.setText("3");
        Bttn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn3ActionPerformed(evt);
            }
        });

        Bttn0.setText("0");
        Bttn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bttn0ActionPerformed(evt);
            }
        });

        FieldXMax.setEditable(false);

        LabelXMax.setText("XMax = ");

        BttnKlar.setText("Klar");
        BttnKlar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnKlarActionPerformed(evt);
            }
        });

        BttnClear.setText("C");
        BttnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnClearActionPerformed(evt);
            }
        });

        BttnBack.setText("←");
        BttnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelXMax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldXMax))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Bttn4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bttn5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bttn6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Bttn0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(Bttn1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Bttn2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Bttn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BttnPunkt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Bttn7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bttn8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bttn9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BttnKlar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BttnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(BttnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldXMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelXMax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bttn7)
                            .addComponent(Bttn8)
                            .addComponent(Bttn9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bttn4)
                            .addComponent(Bttn5)
                            .addComponent(Bttn6)))
                    .addComponent(BttnKlar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bttn1)
                    .addComponent(Bttn2)
                    .addComponent(Bttn3)
                    .addComponent(BttnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bttn0)
                    .addComponent(BttnPunkt)
                    .addComponent(BttnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Bttn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn7ActionPerformed
        FieldXMax.setText(FieldXMax.getText()+"7"); //Adds the number "7" to the textfield
    }//GEN-LAST:event_Bttn7ActionPerformed

    private void BttnPunktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnPunktActionPerformed
        FieldXMax.setText(FieldXMax.getText()+"."); //Adds a "." to the textfield
    }//GEN-LAST:event_BttnPunktActionPerformed

    private void Bttn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn8ActionPerformed
        FieldXMax.setText(FieldXMax.getText()+"8"); //Adds the number "8" to the textfield
    }//GEN-LAST:event_Bttn8ActionPerformed

    private void Bttn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn9ActionPerformed
        FieldXMax.setText(FieldXMax.getText()+"9"); //Adds the number "9" to the textfield
    }//GEN-LAST:event_Bttn9ActionPerformed

    private void Bttn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn6ActionPerformed
        FieldXMax.setText(FieldXMax.getText()+"6"); //Adds the number "6" to the textfield
    }//GEN-LAST:event_Bttn6ActionPerformed

    private void Bttn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn5ActionPerformed
        FieldXMax.setText(FieldXMax.getText()+"5"); //Adds the number "5" to the textfield
    }//GEN-LAST:event_Bttn5ActionPerformed

    private void Bttn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn4ActionPerformed
        FieldXMax.setText(FieldXMax.getText()+"4"); //Adds the number "4" to the textfield
    }//GEN-LAST:event_Bttn4ActionPerformed

    private void Bttn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn1ActionPerformed
        FieldXMax.setText(FieldXMax.getText()+"1"); //Adds the number "1" to the textfield
    }//GEN-LAST:event_Bttn1ActionPerformed

    private void Bttn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn2ActionPerformed
        FieldXMax.setText(FieldXMax.getText()+"2"); //Adds the number "2" to the textfield
    }//GEN-LAST:event_Bttn2ActionPerformed

    private void Bttn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn3ActionPerformed
        FieldXMax.setText(FieldXMax.getText()+"3"); //Adds the number "3" to the textfield
    }//GEN-LAST:event_Bttn3ActionPerformed

    private void Bttn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bttn0ActionPerformed

        FieldXMax.setText(FieldXMax.getText()+"0"); //Adds the number "0" to the textfield
    }//GEN-LAST:event_Bttn0ActionPerformed

    private void BttnKlarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnKlarActionPerformed
     PanelRaknare.XMax = Double.parseDouble(FieldXMax.getText());
   
    }//GEN-LAST:event_BttnKlarActionPerformed

    private void BttnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnClearActionPerformed
        FieldXMax.setText("");
    }//GEN-LAST:event_BttnClearActionPerformed

    private void BttnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnBackActionPerformed
        String Bort = FieldXMax.getText();
        int langdBort = Bort.length();
        Bort = Bort.substring(0, langdBort-1);
        FieldXMax.setText(Bort);
    }//GEN-LAST:event_BttnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bttn0;
    private javax.swing.JButton Bttn1;
    private javax.swing.JButton Bttn2;
    private javax.swing.JButton Bttn3;
    private javax.swing.JButton Bttn4;
    private javax.swing.JButton Bttn5;
    private javax.swing.JButton Bttn6;
    private javax.swing.JButton Bttn7;
    private javax.swing.JButton Bttn8;
    private javax.swing.JButton Bttn9;
    private javax.swing.JButton BttnBack;
    private javax.swing.JButton BttnClear;
    private javax.swing.JButton BttnKlar;
    private javax.swing.JButton BttnPunkt;
    private javax.swing.JTextField FieldXMax;
    private javax.swing.JLabel LabelXMax;
    // End of variables declaration//GEN-END:variables
}
